# -*- coding: utf-8 -*-
"""Ass10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p3ZthKHcMKLWu9-Py-t_eL9G19EjdKTS
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv("/content/demo.csv")
df

import numpy as np
from scipy import stats

z = np.abs(stats.zscore(df['math score']))

print(z)

threshold = 0.18

sample_outliers = np.where(z <threshold)
sample_outliers

col = ['reading score']
df.boxplot(col)

sorted_rscore= sorted(df['reading score'])
sorted_rscore
median=np.median(sorted_rscore)
median

refined_df=df

refined_df['reading score'] = np.where(refined_df['reading score'] > sorted_rscore ,median,refined_df['reading score'])
refined_df











