# -*- coding: utf-8 -*-
"""Ass12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A5A7ebgUiK788Jgtcn7l8QsJmAQGGVhp
"""

import numpy as np
import pandas as pd
df=pd.read_csv("/demo.csv")
df

sorted_rscore= sorted(df['reading score'])

sorted_rscore

q1 = np.percentile(sorted_rscore, 25)
q3 = np.percentile(sorted_rscore, 75)
print(q1,q3)

IQR = q3-q1

lwr_bound = q1-(1.5*IQR)
upr_bound = q3+(1.5*IQR)
print(lwr_bound, upr_bound)

r_outliers = []
for i in sorted_rscore:
  if(i<lwr_bound or i>upr_bound):
    r_outliers.append(i)
print(r_outliers)

col = ['reading score']
df.boxplot(col)

median=np.median(sorted_rscore)
median

refined_df=df
refined_df['reading score'] = np.where(refined_df['reading score'] >upr_bound, median,refined_df['reading score'])

refined_df['reading score'] = np.where(refined_df['reading score'] <lwr_bound, median,refined_df['reading score'])

col = ['reading score']
refined_df.boxplot(col)







