# -*- coding: utf-8 -*-
"""Ass9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R18zCWtHQLQpW0Lyj9RvDDvTskznatda
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/demo.csv")
df

col = ['math score', 'reading score' , 'writing score','placement score']
df.boxplot(col)

print(np.where(df['math score']>90))
print(np.where(df['reading score']<25))
print(np.where(df['writing score']<30))

df_stud=df
ninetieth_percentile = np.percentile(df_stud['math score'], 90)
b = np.where(df_stud['math score']>ninetieth_percentile,ninetieth_percentile, df_stud['math score'])
print("New array:",b)

df_stud.insert(1,"m score",b,True)
df_stud

col = ['reading score']
df.boxplot(col)











