# -*- coding: utf-8 -*-
"""Assignment 8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nMVRtErYMUFJaroV4KVHJNENwav2ozag
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/StudentsPerformanceTest1.csv")
df.head()

df.isnull()

df.isnull().sum()

ndf = df
new_data = ndf.dropna(axis = 0, how ='any')
new_data

ndf = df
ndf.dropna(how = 'all')

df.dropna(axis='columns')







